# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserLogin = channel.unary_unary(
                '/library.LibraryService/UserLogin',
                request_serializer=library__pb2.LoginRequest.SerializeToString,
                response_deserializer=library__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.CreateBook = channel.unary_unary(
                '/library.LibraryService/CreateBook',
                request_serializer=library__pb2.Book.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SearchBooks = channel.unary_stream(
                '/library.LibraryService/SearchBooks',
                request_serializer=library__pb2.SearchRequest.SerializeToString,
                response_deserializer=library__pb2.Book.FromString,
                _registered_method=True)
        self.GetAllUsers = channel.unary_stream(
                '/library.LibraryService/GetAllUsers',
                request_serializer=library__pb2.SearchRequest.SerializeToString,
                response_deserializer=library__pb2.UserDetail.FromString,
                _registered_method=True)
        self.GetUserDetail = channel.unary_unary(
                '/library.LibraryService/GetUserDetail',
                request_serializer=library__pb2.UserIdRequest.SerializeToString,
                response_deserializer=library__pb2.UserDetail.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/library.LibraryService/DeleteUser',
                request_serializer=library__pb2.UserIdRequest.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateClient = channel.unary_unary(
                '/library.LibraryService/CreateClient',
                request_serializer=library__pb2.Client.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetAllClients = channel.unary_stream(
                '/library.LibraryService/GetAllClients',
                request_serializer=library__pb2.SearchRequest.SerializeToString,
                response_deserializer=library__pb2.Client.FromString,
                _registered_method=True)
        self.GetClient = channel.unary_unary(
                '/library.LibraryService/GetClient',
                request_serializer=library__pb2.ClientIdRequest.SerializeToString,
                response_deserializer=library__pb2.Client.FromString,
                _registered_method=True)
        self.UpdateClient = channel.unary_unary(
                '/library.LibraryService/UpdateClient',
                request_serializer=library__pb2.Client.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteClient = channel.unary_unary(
                '/library.LibraryService/DeleteClient',
                request_serializer=library__pb2.ClientIdRequest.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)


class LibraryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserLogin(self, request, context):
        """-------- AUTH --------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBook(self, request, context):
        """-------- BOOK --------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """-------- USERS --------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateClient(self, request, context):
        """-------- CLIENTS --------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllClients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.UserLogin,
                    request_deserializer=library__pb2.LoginRequest.FromString,
                    response_serializer=library__pb2.LoginResponse.SerializeToString,
            ),
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=library__pb2.Book.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'SearchBooks': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchBooks,
                    request_deserializer=library__pb2.SearchRequest.FromString,
                    response_serializer=library__pb2.Book.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=library__pb2.SearchRequest.FromString,
                    response_serializer=library__pb2.UserDetail.SerializeToString,
            ),
            'GetUserDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserDetail,
                    request_deserializer=library__pb2.UserIdRequest.FromString,
                    response_serializer=library__pb2.UserDetail.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=library__pb2.UserIdRequest.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'CreateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClient,
                    request_deserializer=library__pb2.Client.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'GetAllClients': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllClients,
                    request_deserializer=library__pb2.SearchRequest.FromString,
                    response_serializer=library__pb2.Client.SerializeToString,
            ),
            'GetClient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClient,
                    request_deserializer=library__pb2.ClientIdRequest.FromString,
                    response_serializer=library__pb2.Client.SerializeToString,
            ),
            'UpdateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClient,
                    request_deserializer=library__pb2.Client.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteClient,
                    request_deserializer=library__pb2.ClientIdRequest.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.LibraryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/UserLogin',
            library__pb2.LoginRequest.SerializeToString,
            library__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/CreateBook',
            library__pb2.Book.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/library.LibraryService/SearchBooks',
            library__pb2.SearchRequest.SerializeToString,
            library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/library.LibraryService/GetAllUsers',
            library__pb2.SearchRequest.SerializeToString,
            library__pb2.UserDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/GetUserDetail',
            library__pb2.UserIdRequest.SerializeToString,
            library__pb2.UserDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/DeleteUser',
            library__pb2.UserIdRequest.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/CreateClient',
            library__pb2.Client.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/library.LibraryService/GetAllClients',
            library__pb2.SearchRequest.SerializeToString,
            library__pb2.Client.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/GetClient',
            library__pb2.ClientIdRequest.SerializeToString,
            library__pb2.Client.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/UpdateClient',
            library__pb2.Client.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/DeleteClient',
            library__pb2.ClientIdRequest.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
