# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserLogin = channel.unary_unary(
                '/library_system.LibraryService/UserLogin',
                request_serializer=library__pb2.LoginRequest.SerializeToString,
                response_deserializer=library__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.CreateMember = channel.unary_unary(
                '/library_system.LibraryService/CreateMember',
                request_serializer=library__pb2.Member.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/library_system.LibraryService/UpdateMember',
                request_serializer=library__pb2.Member.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteMember = channel.unary_unary(
                '/library_system.LibraryService/DeleteMember',
                request_serializer=library__pb2.UserIdRequest.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetAllMembers = channel.unary_stream(
                '/library_system.LibraryService/GetAllMembers',
                request_serializer=library__pb2.SearchRequest.SerializeToString,
                response_deserializer=library__pb2.Member.FromString,
                _registered_method=True)
        self.GetMemberDetail = channel.unary_unary(
                '/library_system.LibraryService/GetMemberDetail',
                request_serializer=library__pb2.UserIdRequest.SerializeToString,
                response_deserializer=library__pb2.Member.FromString,
                _registered_method=True)
        self.CreateBook = channel.unary_unary(
                '/library_system.LibraryService/CreateBook',
                request_serializer=library__pb2.Book.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SearchBooks = channel.unary_stream(
                '/library_system.LibraryService/SearchBooks',
                request_serializer=library__pb2.SearchRequest.SerializeToString,
                response_deserializer=library__pb2.Book.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/library_system.LibraryService/GetBook',
                request_serializer=library__pb2.SearchRequest.SerializeToString,
                response_deserializer=library__pb2.Book.FromString,
                _registered_method=True)
        self.UpdateBookAvailability = channel.unary_unary(
                '/library_system.LibraryService/UpdateBookAvailability',
                request_serializer=library__pb2.Book.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.BorrowBook = channel.unary_unary(
                '/library_system.LibraryService/BorrowBook',
                request_serializer=library__pb2.BorrowRequest.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/library_system.LibraryService/ReturnBook',
                request_serializer=library__pb2.BorrowRequest.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetAllUsers = channel.unary_stream(
                '/library_system.LibraryService/GetAllUsers',
                request_serializer=library__pb2.SearchRequest.SerializeToString,
                response_deserializer=library__pb2.UserDetail.FromString,
                _registered_method=True)
        self.GetUserDetail = channel.unary_unary(
                '/library_system.LibraryService/GetUserDetail',
                request_serializer=library__pb2.UserIdRequest.SerializeToString,
                response_deserializer=library__pb2.UserDetail.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/library_system.LibraryService/DeleteUser',
                request_serializer=library__pb2.UserIdRequest.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateStaffProfile = channel.unary_unary(
                '/library_system.LibraryService/UpdateStaffProfile',
                request_serializer=library__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=library__pb2.StatusResponse.FromString,
                _registered_method=True)


class LibraryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemberDetail(self, request, context):
        """<--- AJOUT DU POINT-VIRGULE ICI
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBookAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStaffProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.UserLogin,
                    request_deserializer=library__pb2.LoginRequest.FromString,
                    response_serializer=library__pb2.LoginResponse.SerializeToString,
            ),
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=library__pb2.Member.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=library__pb2.Member.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteMember': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMember,
                    request_deserializer=library__pb2.UserIdRequest.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'GetAllMembers': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllMembers,
                    request_deserializer=library__pb2.SearchRequest.FromString,
                    response_serializer=library__pb2.Member.SerializeToString,
            ),
            'GetMemberDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemberDetail,
                    request_deserializer=library__pb2.UserIdRequest.FromString,
                    response_serializer=library__pb2.Member.SerializeToString,
            ),
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=library__pb2.Book.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'SearchBooks': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchBooks,
                    request_deserializer=library__pb2.SearchRequest.FromString,
                    response_serializer=library__pb2.Book.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=library__pb2.SearchRequest.FromString,
                    response_serializer=library__pb2.Book.SerializeToString,
            ),
            'UpdateBookAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBookAvailability,
                    request_deserializer=library__pb2.Book.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=library__pb2.BorrowRequest.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=library__pb2.BorrowRequest.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=library__pb2.SearchRequest.FromString,
                    response_serializer=library__pb2.UserDetail.SerializeToString,
            ),
            'GetUserDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserDetail,
                    request_deserializer=library__pb2.UserIdRequest.FromString,
                    response_serializer=library__pb2.UserDetail.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=library__pb2.UserIdRequest.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateStaffProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStaffProfile,
                    request_deserializer=library__pb2.UpdateProfileRequest.FromString,
                    response_serializer=library__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library_system.LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library_system.LibraryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/UserLogin',
            library__pb2.LoginRequest.SerializeToString,
            library__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/CreateMember',
            library__pb2.Member.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/UpdateMember',
            library__pb2.Member.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/DeleteMember',
            library__pb2.UserIdRequest.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/library_system.LibraryService/GetAllMembers',
            library__pb2.SearchRequest.SerializeToString,
            library__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemberDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/GetMemberDetail',
            library__pb2.UserIdRequest.SerializeToString,
            library__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/CreateBook',
            library__pb2.Book.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/library_system.LibraryService/SearchBooks',
            library__pb2.SearchRequest.SerializeToString,
            library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/GetBook',
            library__pb2.SearchRequest.SerializeToString,
            library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBookAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/UpdateBookAvailability',
            library__pb2.Book.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/BorrowBook',
            library__pb2.BorrowRequest.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/ReturnBook',
            library__pb2.BorrowRequest.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/library_system.LibraryService/GetAllUsers',
            library__pb2.SearchRequest.SerializeToString,
            library__pb2.UserDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/GetUserDetail',
            library__pb2.UserIdRequest.SerializeToString,
            library__pb2.UserDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/DeleteUser',
            library__pb2.UserIdRequest.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStaffProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library_system.LibraryService/UpdateStaffProfile',
            library__pb2.UpdateProfileRequest.SerializeToString,
            library__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
