# Generated by Django 4.2.14 on 2025-12-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('emprunts_actifs', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_inscription'],
            },
        ),
    ]
