# Generated by Django 4.2.14 on 2025-12-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=20),
        ),
    ]
