# Generated by Django 4.2.14 on 2025-12-27 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, verbose_name='Titre du livre')),
                ('borrower_name', models.CharField(max_length=100, verbose_name="Nom de l'emprunteur")),
                ('borrower_email', models.EmailField(max_length=254, verbose_name="Email de l'emprunteur")),
                ('borrow_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'emprunt")),
                ('return_date', models.DateField(verbose_name='Date de retour prévue')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='Date de retour réelle')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('returned', 'Retourné'), ('overdue', 'En Retard')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
