# Generated by Django 4.2.14 on 2026-01-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0003_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
