# Generated by Django 4.2.14 on 2026-01-02 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0005_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='patron',
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_admin.member'),
        ),
    ]
